import { jsPDF } from 'jspdf';

interface PdfExportOptions {
  title?: string;
  author?: string;
  pageSize?: 'a4' | 'letter';
  margins?: {
    top: number;
    right: number;
    bottom: number;
    left: number;
  };
}

const DEFAULT_OPTIONS: Required<PdfExportOptions> = {
  title: 'AI Playground Export',
  author: 'AI Playground',
  pageSize: 'a4',
  margins: { top: 20, right: 20, bottom: 20, left: 20 },
};

/**
 * Export text content to PDF
 */
export async function exportToPdf(
  content: string,
  options: PdfExportOptions = {}
): Promise<Blob> {
  const opts = { ...DEFAULT_OPTIONS, ...options };
  
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: opts.pageSize,
  });

  // Set document properties
  doc.setProperties({
    title: opts.title,
    author: opts.author,
    creator: 'AI Playground',
  });

  // Calculate text area
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const textWidth = pageWidth - opts.margins.left - opts.margins.right;
  
  // Add title
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(opts.title, opts.margins.left, opts.margins.top + 10);

  // Add content
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  
  const lines = doc.splitTextToSize(content, textWidth);
  let y = opts.margins.top + 25;
  const lineHeight = 6;

  for (const line of lines) {
    if (y + lineHeight > pageHeight - opts.margins.bottom) {
      doc.addPage();
      y = opts.margins.top;
    }
    doc.text(line, opts.margins.left, y);
    y += lineHeight;
  }

  // Add footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(128);
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
    doc.text(
      `Generated by AI Playground`,
      pageWidth - opts.margins.right,
      pageHeight - 10,
      { align: 'right' }
    );
  }

  return doc.output('blob');
}

/**
 * Export conversation to PDF
 */
export async function exportConversationToPdf(
  messages: { role: string; content: string }[],
  title?: string
): Promise<Blob> {
  const content = messages
    .map((msg) => `[${msg.role.toUpperCase()}]\n${msg.content}`)
    .join('\n\n---\n\n');

  return exportToPdf(content, { title: title || 'Chat Conversation' });
}

/**
 * Export research report to PDF
 */
export async function exportResearchToPdf(
  question: string,
  synthesis: string,
  citations?: { title: string; url: string }[]
): Promise<Blob> {
  let content = `RESEARCH QUESTION:\n${question}\n\n`;
  content += `SYNTHESIZED ANSWER:\n${synthesis}`;
  
  if (citations && citations.length > 0) {
    content += '\n\n---\n\nSOURCES:\n';
    citations.forEach((cite, i) => {
      content += `${i + 1}. ${cite.title}\n   ${cite.url}\n`;
    });
  }

  return exportToPdf(content, { title: 'Research Report' });
}

