'use client';

import { useState } from 'react';
import type { DeepSearchQuery } from '@/lib/types';
import { Button } from '@/components/ui/button';
import { cn, copyToClipboard, downloadBlob } from '@/lib/utils';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { 
  FileText, 
  Copy, 
  Check, 
  Download, 
  ExternalLink,
  RefreshCw,
  BookOpen
} from 'lucide-react';

interface ResearchReportProps {
  query: DeepSearchQuery;
  onNewSearch: () => void;
}

export function ResearchReport({ query, onNewSearch }: ResearchReportProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    if (!query.synthesis) return;
    await copyToClipboard(query.synthesis);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExport = () => {
    if (!query.synthesis) return;

    const content = `# Research Report

## Question
${query.question}

## Answer
${query.synthesis}

## Sources
${query.citations?.map((c, i) => `${i + 1}. [${c.title}](${c.url})`).join('\n') || 'No sources available'}

---
Generated by AI Playground DeepSearch
`;

    const blob = new Blob([content], { type: 'text/markdown' });
    downloadBlob(blob, `research-report-${Date.now()}.md`);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-start justify-between gap-4">
        <div>
          <h2 className="text-lg font-semibold text-[var(--foreground)] mb-1">
            Research Complete
          </h2>
          <p className="text-sm text-[var(--foreground-muted)]">
            {query.question}
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" onClick={handleCopy}>
            {copied ? (
              <Check className="w-4 h-4" />
            ) : (
              <Copy className="w-4 h-4" />
            )}
          </Button>
          <Button variant="outline" size="sm" onClick={handleExport}>
            <Download className="w-4 h-4" />
          </Button>
          <Button variant="outline" size="sm" onClick={onNewSearch}>
            <RefreshCw className="w-4 h-4" />
          </Button>
        </div>
      </div>

      {/* Synthesis */}
      <div className="rounded-xl border border-[var(--border)] bg-[var(--background-secondary)] overflow-hidden">
        <div className="flex items-center gap-2 px-4 py-3 border-b border-[var(--border)] bg-[var(--background-tertiary)]">
          <FileText className="w-4 h-4 text-[var(--accent-cyan)]" />
          <span className="text-sm font-medium text-[var(--foreground)]">
            Synthesized Answer
          </span>
        </div>
        <div className="p-4 markdown-content prose prose-invert prose-sm max-w-none">
          <ReactMarkdown remarkPlugins={[remarkGfm]}>
            {query.synthesis || ''}
          </ReactMarkdown>
        </div>
      </div>

      {/* Sources */}
      {query.citations && query.citations.length > 0 && (
        <div className="rounded-xl border border-[var(--border)] bg-[var(--background-secondary)] overflow-hidden">
          <div className="flex items-center gap-2 px-4 py-3 border-b border-[var(--border)] bg-[var(--background-tertiary)]">
            <BookOpen className="w-4 h-4 text-[var(--accent-amber)]" />
            <span className="text-sm font-medium text-[var(--foreground)]">
              Sources ({query.citations.length})
            </span>
          </div>
          <div className="p-4 space-y-2">
            {query.citations.map((citation, index) => (
              <a
                key={citation.id}
                href={citation.url}
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center gap-3 p-3 rounded-lg bg-[var(--background-tertiary)] hover:bg-[var(--border)] transition-colors group"
              >
                <span className="text-xs font-mono text-[var(--foreground-muted)] w-6">
                  [{index + 1}]
                </span>
                <span className="flex-1 text-sm text-[var(--foreground)] truncate">
                  {citation.title || citation.url}
                </span>
                <ExternalLink className="w-4 h-4 text-[var(--foreground-muted)] group-hover:text-[var(--accent-cyan)] transition-colors" />
              </a>
            ))}
          </div>
        </div>
      )}

      {/* Sub-question Results (collapsed by default) */}
      {query.searchResults && query.searchResults.length > 0 && (
        <details className="rounded-xl border border-[var(--border)] bg-[var(--background-secondary)] overflow-hidden">
          <summary className="flex items-center gap-2 px-4 py-3 cursor-pointer hover:bg-[var(--background-tertiary)] transition-colors">
            <span className="text-sm font-medium text-[var(--foreground)]">
              Detailed Research ({query.searchResults.length} sub-queries)
            </span>
          </summary>
          <div className="p-4 space-y-4 border-t border-[var(--border)]">
            {query.searchResults.map((result, index) => (
              <div key={index} className="space-y-2">
                <h4 className="text-sm font-medium text-[var(--accent-cyan)]">
                  {index + 1}. {result.question}
                </h4>
                <div className="text-sm text-[var(--foreground-muted)] pl-4 border-l-2 border-[var(--border)]">
                  {result.answer.slice(0, 500)}
                  {result.answer.length > 500 && '...'}
                </div>
              </div>
            ))}
          </div>
        </details>
      )}
    </div>
  );
}

